pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - go env
      - go get
      - go build
      - go test
  slack:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: ci

